[project]
name = "cosmos"
version = "1.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bronze-silver-functions",
    "databricks-connect>=18.1.0",
    "fastapi>=0.135.3",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "tenacity>=9.1.4",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["."]
exclude = [".venv*", "tests*"]

[tool.uv.sources]
bronze-silver-functions = { git = "https://github.com/manolis1997/bronze_silver_functions.git" }

[dependency-groups]
dev = [
    "pytest-xdist>=3.8.0",
    "python-semantic-release>=10.5.3",
]
prod = [
    "pydantic>=2.13.0",
]
stg = [
    "great-expectations>=1.17.2",
]


[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
commit_parser = "custom"
branch = "production"
upload_to_pypi = false
build_command = "pip install uv && uv build"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"