[project]
name = "cosmos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bronze-silver-functions",
    "databricks-connect>=18.1.0",
    "fastapi>=0.135.3",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "tenacity>=9.1.4",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["."]
exclude = [".venv*", "tests*"]

[tool.uv.sources]
bronze-silver-functions = { git = "https://github.com/manolis1997/bronze_silver_functions.git" }

