name: Seed Cache

on:
    push:
        branches:
            - development

jobs:
    seed-cache:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        env:
            UV_CACHE_DIR: ~/.cache/uv
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Cache uv dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/uv
                key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
                restore-keys: |
                  ${{ runner.os }}-uv-

            - name: Install uv and sync dependencies
              run: |
                pip install uv
                uv sync
