name: SCD App

on:
    pull_request:
        branches:
            - development

jobs:
    test:
        runs-on: ubuntu-latest
        environment: dev
        defaults:
            run:
                working-directory: ./pipeline/

        env:
          DATABRICKS_HOST: https://adb-1738163877178133.13.azuredatabricks.net/
          DATABRICKS_CLIENT_ID: ${{secrets.DEV_SP_CLIENT_ID}}
          DATABRICKS_CLIENT_SECRET: ${{secrets.DEV_SP_CLIENT_SECRET}}                                                                                                                                                                                                                              
          DATABRICKS_CLUSTER_ID: ${{secrets.DEV_CLUSTER_ID}}   
        steps:
            - name: Checkout code # Pull the repo into ubuntu system
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            
            - name: Install Databricks CLI
              run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
            
            - name: Databricks CLI Version
              run: databricks -v
            
            - name: Configure Databricks CLI Authentication
              run: |
                printf '[DEFAULT]\nhost = %s\nclient_id = %s\nclient_secret = %s\ncluster_id = %s\n' \
                  "$DATABRICKS_HOST" "$DATABRICKS_CLIENT_ID" "$DATABRICKS_CLIENT_SECRET" "$DATABRICKS_CLUSTER_ID" \
                  > ~/.databrickscfg

            - name: Print Databrickscfg
              run: cat ~/.databrickscfg  
            
            - name: Databricks Auth Profiles
              run: databricks auth profiles
            
            - name: Install uv
              run: pip install uv

            - name: Install uv dependencies
              run: uv sync
            
            - name: Run the Code
              run: uv run python pipeline_code.py --table product --load FL
        
