# CI Pipeline
name: SCD App

on:
    pull_request:
        branches:
            - development
            - staging
            - production
jobs:
    CI:
        runs-on: ubuntu-latest
        environment: dev
        permissions:
          actions: write
          contents: read
        defaults:
            run:
                working-directory: ./pipeline/
        env:
          DATABRICKS_HOST: https://adb-1738163877178133.13.azuredatabricks.net/
          DATABRICKS_CLIENT_ID: ${{secrets.DEV_SP_CLIENT_ID}}
          DATABRICKS_CLIENT_SECRET: ${{secrets.DEV_SP_CLIENT_SECRET}}                                                                                                                                                                                                                              
          DATABRICKS_CLUSTER_ID: ${{secrets.DEV_CLUSTER_ID}}   
        steps:
            - name: Checkout code # Pull the repo into ubuntu system
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Install uv
              uses: actions/cache@v4
              env:
                cache-name: cache-uv-modules
              with:
                path: ~/.cache/uv
                key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
                restore-keys: |
                  ${{ runner.os }}-uv-
                
            - name: Initialise Environment # Set up the ENV
              run: bash ../scripts/init.sh
            
            - name: Run the Code
              run: uv run python pipeline_code.py --table product --load CDC
